# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'checkst.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(525, 525)
        Dialog.setMinimumSize(QtCore.QSize(525, 525))
        Dialog.setMaximumSize(QtCore.QSize(525, 525))
        self.frame = QtGui.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(0, 0, 525, 525))
        self.frame.setMinimumSize(QtCore.QSize(525, 525))
        self.frame.setMaximumSize(QtCore.QSize(525, 525))
        self.frame.setStyleSheet(_fromUtf8("QFrame{background-color:white}"))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.label = QtGui.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 20, 161, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("KoPub돋움체 Bold"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 361, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("KoPub돋움체 Light"))
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet(_fromUtf8("QLabel{color:rgb(77, 77, 77)}"))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_5 = QtGui.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(20, 100, 361, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("KoPub돋움체 Light"))
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet(_fromUtf8("QLabel{color:rgb(77, 77, 77)}"))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(20, 130, 361, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("KoPub돋움체 Light"))
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet(_fromUtf8("QLabel{color:rgb(77, 77, 77)}"))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_6 = QtGui.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(20, 160, 361, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("KoPub돋움체 Light"))
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet(_fromUtf8("QLabel{color:rgb(77, 77, 77)}"))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(20, 190, 361, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("KoPub돋움체 Light"))
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet(_fromUtf8("QLabel{color:rgb(77, 77, 77)}"))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.st_1 = QtGui.QLabel(self.frame)
        self.st_1.setGeometry(QtCore.QRect(220, 70, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("KoPub돋움체 Bold"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.st_1.setFont(font)
        self.st_1.setStyleSheet(_fromUtf8("QLabel{color:rgb(77, 77, 77)}"))
        self.st_1.setText(_fromUtf8(""))
        self.st_1.setObjectName(_fromUtf8("st_1"))
        self.st_2 = QtGui.QLabel(self.frame)
        self.st_2.setGeometry(QtCore.QRect(330, 100, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("KoPub돋움체 Bold"))
        font.setPointSize(12)
        self.st_2.setFont(font)
        self.st_2.setStyleSheet(_fromUtf8("QLabel{color:rgb(77, 77, 77)}"))
        self.st_2.setText(_fromUtf8(""))
        self.st_2.setObjectName(_fromUtf8("st_2"))
        self.st_3 = QtGui.QLabel(self.frame)
        self.st_3.setGeometry(QtCore.QRect(170, 130, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("KoPub돋움체 Bold"))
        font.setPointSize(12)
        self.st_3.setFont(font)
        self.st_3.setStyleSheet(_fromUtf8("QLabel{color:rgb(77, 77, 77)}"))
        self.st_3.setText(_fromUtf8(""))
        self.st_3.setObjectName(_fromUtf8("st_3"))
        self.st_4 = QtGui.QLabel(self.frame)
        self.st_4.setGeometry(QtCore.QRect(200, 160, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("KoPub돋움체 Bold"))
        font.setPointSize(12)
        self.st_4.setFont(font)
        self.st_4.setStyleSheet(_fromUtf8("QLabel{color:rgb(77, 77, 77)}"))
        self.st_4.setText(_fromUtf8(""))
        self.st_4.setObjectName(_fromUtf8("st_4"))
        self.st_5 = QtGui.QLabel(self.frame)
        self.st_5.setGeometry(QtCore.QRect(230, 190, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("KoPub돋움체 Bold"))
        font.setPointSize(12)
        self.st_5.setFont(font)
        self.st_5.setStyleSheet(_fromUtf8("QLabel{color:rgb(77, 77, 77)}"))
        self.st_5.setText(_fromUtf8(""))
        self.st_5.setObjectName(_fromUtf8("st_5"))
        self.autostart = QtGui.QPushButton(self.frame)
        self.autostart.setGeometry(QtCore.QRect(370, 480, 121, 23))
        self.autostart.setObjectName(_fromUtf8("autostart"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.label.setText(_translate("Dialog", "점검상태", None))
        self.label_2.setText(_translate("Dialog", "바이러스 백신 업데이트 점검", None))
        self.label_5.setText(_translate("Dialog", "한글프로그램의 최신 보안 패치 설치 여부 점검", None))
        self.label_3.setText(_translate("Dialog", "로그인 패스워드 점검", None))
        self.label_6.setText(_translate("Dialog", "화면보호기 설정 여부 점검", None))
        self.label_7.setText(_translate("Dialog", "USB 자동 실행 허용 여부 점검", None))
        self.autostart.setText(_translate("Dialog", "취약점 자동개선", None))

