# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'checkmn.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(525, 525)
        Dialog.setMinimumSize(QtCore.QSize(525, 525))
        Dialog.setMaximumSize(QtCore.QSize(525, 525))
        self.frame = QtGui.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(0, 0, 525, 525))
        self.frame.setMinimumSize(QtCore.QSize(525, 525))
        self.frame.setMaximumSize(QtCore.QSize(525, 525))
        self.frame.setStyleSheet(_fromUtf8("QFrame{background-color:white}"))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.checkBox_1 = QtGui.QCheckBox(self.frame)
        self.checkBox_1.setEnabled(True)
        self.checkBox_1.setGeometry(QtCore.QRect(20, 90, 221, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("KoPub돋움체 Light"))
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.checkBox_1.setFont(font)
        self.checkBox_1.setCheckable(False)
        self.checkBox_1.setObjectName(_fromUtf8("checkBox_1"))
        self.checkBox_2 = QtGui.QCheckBox(self.frame)
        self.checkBox_2.setGeometry(QtCore.QRect(20, 130, 321, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("KoPub돋움체 Light"))
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setCheckable(False)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.checkBox_3 = QtGui.QCheckBox(self.frame)
        self.checkBox_3.setGeometry(QtCore.QRect(20, 170, 221, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("KoPub돋움체 Light"))
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setCheckable(False)
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.checkBox_4 = QtGui.QCheckBox(self.frame)
        self.checkBox_4.setGeometry(QtCore.QRect(20, 210, 221, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("KoPub돋움체 Light"))
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setCheckable(False)
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.checkBox_5 = QtGui.QCheckBox(self.frame)
        self.checkBox_5.setGeometry(QtCore.QRect(20, 250, 221, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("KoPub돋움체 Light"))
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_5.setFont(font)
        self.checkBox_5.setCheckable(False)
        self.checkBox_5.setObjectName(_fromUtf8("checkBox_5"))
        self.label = QtGui.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 20, 161, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("KoPub돋움체 Bold"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(40, 110, 281, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("KoPub돋움체 Light"))
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet(_fromUtf8("QLabel{color:rgb(77, 77, 77)}"))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(40, 150, 281, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("KoPub돋움체 Light"))
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet(_fromUtf8("QLabel{color:rgb(77, 77, 77)}"))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(40, 190, 321, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("KoPub돋움체 Light"))
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet(_fromUtf8("QLabel{color:rgb(77, 77, 77)}"))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_6 = QtGui.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(40, 230, 281, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("KoPub돋움체 Light"))
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet(_fromUtf8("QLabel{color:rgb(77, 77, 77)}"))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_8 = QtGui.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(40, 270, 281, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("KoPub돋움체 Light"))
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet(_fromUtf8("QLabel{color:rgb(77, 77, 77)}"))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.pushButton = QtGui.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(380, 470, 121, 23))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.checkBox_1.setText(_translate("Dialog", "바이러스 백신 업데이트 점검", None))
        self.checkBox_2.setText(_translate("Dialog", "한글프로그램의 최신 보안 패치 설치 여부 점검", None))
        self.checkBox_3.setText(_translate("Dialog", "로그인 패스워드 점검", None))
        self.checkBox_4.setText(_translate("Dialog", "화면보호기 설정 여부 점검", None))
        self.checkBox_5.setText(_translate("Dialog", "USB 자동 실행 허용 여부 점검", None))
        self.label.setText(_translate("Dialog", "점검항목", None))
        self.label_2.setText(_translate("Dialog", "바이러스 백신의 최신 업데이트 상태를 점검합니다.", None))
        self.label_3.setText(_translate("Dialog", "바이러스 백신의 최신 업데이트 상태를 점검합니다.", None))
        self.label_4.setText(_translate("Dialog", "윈도우 로그인 패스워드의 최근 2달 변경 여부를 점검 합니다.", None))
        self.label_6.setText(_translate("Dialog", "화면보호기 설정 여부를 점검 합니다.", None))
        self.label_8.setText(_translate("Dialog", "USB 자동실행 허용 여부를 점검 합니다.", None))
        self.pushButton.setText(_translate("Dialog", "점검 시작", None))

